name: KiBot

on:
  push:
    paths:
    - "pcb/*.kicad_sch"
    - "pcb/*.kicad_pcb"
    - "pcb/*.kicad_pro"
    - "**/*kibot.yml"
  pull_request:
    paths:
    - "pcb/*.kicad_sch"
    - "pcb/*.kicad_pcb"
    - "pcb/*.kicad_pro"
    - "**/*kibot.yml"

env:
  schema: "pcb/*.kicad_sch"
  board: "pcb/*.kicad_pcb"
  dir: .

jobs:
  render:
    runs-on: ubuntu-latest
    # needs: [DRC]
    container:
      image: ghcr.io/inti-cmnb/kicad7_auto_full:latest
    steps:
      - uses: actions/checkout@v3
      - name: run kibot
        run: | 
          kibot -c kibot.yml -e ${{env.schema}} -b ${{env.board}} -d ${{env.dir}} -s run_erc,run_drc -v \
            board_black_top.svg board_black_bottom.svg
      - uses: actions/upload-artifact@v3.1.1
        if: ${{success()}}
        with:
          name: ${{github.event.repository.name}}_img
          if-no-files-found: error
          path: |
            ${{env.dir}}/img/**
            !${{env.dir}}/**/*.ogv
            !${{env.dir}}/**/*.log
